name: john
description: BT.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  mobx_codegen: ^2.0.7
  dio: ^4.0.6
  foil: ^0.9.0+1
  blur: ^3.1.0
  sensors_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  ###flutter pub run flutter_native_splash:create
  flutter_native_splash: ^1.0.1+1
  ###flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.0

flutter:

  uses-material-design: true

  assets:
    #Logos
    - lib/main/img/logo.png
    - lib/main/img/shiny.png


flutter_native_splash:
  color: "#121212"
  image: lib/main/img/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/main/img/logo.png"